name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Se recomienda un clon completo para un análisis más completo

      # Configurar el JDK (en caso de que quieras asegurarte de usar Java 17)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Compilar el proyecto usando javac
      - name: Compile Java
        run: |
          mkdir build
          dir /s /b test\src\*.java > sources.txt
          javac -d build @sources.txt
        shell: cmd
        continue-on-error: true
        
      - name: SonarQube Scan
       
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: test
           
